package Formative;

import javax.swing.*;

public class DeOcampo_Pizza extends javax.swing.JFrame {

    public DeOcampo_Pizza() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        double amount = 0;
        
        ButtonGroup pizzaSize = new ButtonGroup();
        ButtonGroup pizzaCrust = new ButtonGroup();
        
        pizzaSize.add(smallPizza);
        pizzaSize.add(mediumPizza);
        pizzaSize.add(largePizza);
        pizzaSize.add(xlargePizza);
        
        pizzaCrust.add(normalCrust);
        pizzaCrust.add(cheesyCrust);
        pizzaCrust.add(sausageCrust);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        placeOrder = new javax.swing.JPanel();
        pizzaSize = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        smallPizza = new javax.swing.JRadioButton();
        mediumPizza = new javax.swing.JRadioButton();
        largePizza = new javax.swing.JRadioButton();
        xlargePizza = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        normalCrust = new javax.swing.JRadioButton();
        cheesyCrust = new javax.swing.JRadioButton();
        sausageCrust = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pepperoni = new javax.swing.JCheckBox();
        extraCheese = new javax.swing.JCheckBox();
        mushroom = new javax.swing.JCheckBox();
        ham = new javax.swing.JCheckBox();
        bacon = new javax.swing.JCheckBox();
        groundBeef = new javax.swing.JCheckBox();
        jalapeno = new javax.swing.JCheckBox();
        pineapple = new javax.swing.JCheckBox();
        driedShrimps = new javax.swing.JCheckBox();
        anchovies = new javax.swing.JCheckBox();
        sunDriedTomatoes = new javax.swing.JCheckBox();
        spinach = new javax.swing.JCheckBox();
        roastedGarlic = new javax.swing.JCheckBox();
        shreddedChicken = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cokeField = new javax.swing.JTextField();
        dCokeField = new javax.swing.JTextField();
        icedTeaField = new javax.swing.JTextField();
        gingerAleField = new javax.swing.JTextField();
        spriteField = new javax.swing.JTextField();
        rootBeerField = new javax.swing.JTextField();
        waterField = new javax.swing.JTextField();
        coke = new javax.swing.JCheckBox();
        dietCoke = new javax.swing.JCheckBox();
        icedTea = new javax.swing.JCheckBox();
        gingerAle = new javax.swing.JCheckBox();
        sprite = new javax.swing.JCheckBox();
        rootBeer = new javax.swing.JCheckBox();
        water = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        chickenWings = new javax.swing.JCheckBox();
        poutine = new javax.swing.JCheckBox();
        onionRings = new javax.swing.JCheckBox();
        cheesyGarlicBread = new javax.swing.JCheckBox();
        garlicDip = new javax.swing.JCheckBox();
        bbqDip = new javax.swing.JCheckBox();
        sourCreamDip = new javax.swing.JCheckBox();
        btnConfirm = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 153, 0));

        placeOrder.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Pizza Size");

        smallPizza.setText("Small ($4.00)");
        smallPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallPizzaActionPerformed(evt);
            }
        });

        mediumPizza.setText("Medium ($7.00)");

        largePizza.setText("Large ($10.00)");

        xlargePizza.setText("Extra Large ($18.00)");

        javax.swing.GroupLayout pizzaSizeLayout = new javax.swing.GroupLayout(pizzaSize);
        pizzaSize.setLayout(pizzaSizeLayout);
        pizzaSizeLayout.setHorizontalGroup(
            pizzaSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizzaSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizzaSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pizzaSizeLayout.createSequentialGroup()
                        .addComponent(smallPizza)
                        .addGap(18, 18, 18)
                        .addComponent(mediumPizza)
                        .addGap(18, 18, 18)
                        .addComponent(largePizza)
                        .addGap(18, 18, 18)
                        .addComponent(xlargePizza))
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pizzaSizeLayout.setVerticalGroup(
            pizzaSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizzaSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pizzaSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallPizza)
                    .addComponent(mediumPizza)
                    .addComponent(largePizza)
                    .addComponent(xlargePizza)))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Crust");

        normalCrust.setText("Normal");
        normalCrust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalCrustActionPerformed(evt);
            }
        });

        cheesyCrust.setText("Cheesy");

        sausageCrust.setText("Sausage");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(normalCrust)
                        .addGap(130, 130, 130)
                        .addComponent(cheesyCrust)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sausageCrust)
                        .addGap(22, 22, 22))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(normalCrust)
                    .addComponent(cheesyCrust)
                    .addComponent(sausageCrust)))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Toppings ($0.75 each)");

        pepperoni.setText("Pepperoni");

        extraCheese.setText("Extra Cheese");

        mushroom.setText("Mushroom");

        ham.setText("Ham");

        bacon.setText("Bacon");

        groundBeef.setText("Ground Beef");

        jalapeno.setText("Jalapeno");

        pineapple.setText("Pineapple");

        driedShrimps.setText("Dried Shrimps");

        anchovies.setText("Anchovies");

        sunDriedTomatoes.setText("Sun Dried Tomatoes");

        spinach.setText("Spinach");

        roastedGarlic.setText("Roasted Garlic");

        shreddedChicken.setText("Shredded Chicken");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pepperoni)
                            .addComponent(extraCheese)
                            .addComponent(mushroom)
                            .addComponent(ham)
                            .addComponent(bacon)
                            .addComponent(groundBeef)
                            .addComponent(jalapeno))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pineapple)
                    .addComponent(driedShrimps)
                    .addComponent(anchovies)
                    .addComponent(sunDriedTomatoes)
                    .addComponent(spinach)
                    .addComponent(roastedGarlic)
                    .addComponent(shreddedChicken))
                .addGap(65, 65, 65))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepperoni)
                    .addComponent(pineapple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extraCheese)
                    .addComponent(driedShrimps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mushroom)
                    .addComponent(anchovies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ham)
                    .addComponent(sunDriedTomatoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bacon)
                    .addComponent(spinach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groundBeef)
                    .addComponent(roastedGarlic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jalapeno)
                    .addComponent(shreddedChicken))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Drinks");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Quantity");

        coke.setText("Coke ($1.45)");

        dietCoke.setText("Diet Coke ($1.45)");

        icedTea.setText("Iced Tea ($1.45)");

        gingerAle.setText("Ginger Ale ($1.45)");

        sprite.setText("Sprite ($1.45)");

        rootBeer.setText("Root Beer ($1.45)");

        water.setText("Water ($1.25)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coke)
                            .addComponent(dietCoke)
                            .addComponent(icedTea)
                            .addComponent(gingerAle)
                            .addComponent(sprite)
                            .addComponent(rootBeer)
                            .addComponent(water))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cokeField)
                            .addComponent(dCokeField)
                            .addComponent(icedTeaField)
                            .addComponent(gingerAleField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spriteField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rootBeerField)
                            .addComponent(waterField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dCokeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dietCoke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icedTeaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icedTea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gingerAleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gingerAle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spriteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rootBeerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rootBeer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(water))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Other Items");

        chickenWings.setText("Chicken Wings ($3.00)");

        poutine.setText("Poutine ($3.00)");

        onionRings.setText("Onion Rings ($3.00)");

        cheesyGarlicBread.setText("Cheesy Garlic Bread ($3.00)");

        garlicDip.setText("Garlic Dip (Free)");

        bbqDip.setText("BBQ Dip (Free)");

        sourCreamDip.setText("Sour Cream Dip (Free)");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poutine)
                            .addComponent(chickenWings)
                            .addComponent(onionRings)
                            .addComponent(cheesyGarlicBread)
                            .addComponent(garlicDip)
                            .addComponent(bbqDip)
                            .addComponent(sourCreamDip))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(chickenWings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poutine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onionRings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cheesyGarlicBread)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(garlicDip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bbqDip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourCreamDip)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirm.setText("Confirm Order");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout placeOrderLayout = new javax.swing.GroupLayout(placeOrder);
        placeOrder.setLayout(placeOrderLayout);
        placeOrderLayout.setHorizontalGroup(
            placeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(placeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pizzaSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(placeOrderLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, placeOrderLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        placeOrderLayout.setVerticalGroup(
            placeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pizzaSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(placeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(placeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smallPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallPizzaActionPerformed

    private void normalCrustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalCrustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalCrustActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        double amount = 0;
        String nl = "\n";
        
        String PizzaSizes = "";
        //Pizza Sizes
        if(smallPizza.isSelected())
        {
            amount = 4.00;
            PizzaSizes = PizzaSizes + "- Small Pizza\n";
        }
        
        if(mediumPizza.isSelected())
        {
            amount = 7.00;
            PizzaSizes = PizzaSizes + "- Medium Pizza\n";
        }
        
        if(largePizza.isSelected())
        {
            amount = 10.00;
            PizzaSizes = PizzaSizes + "- Large Pizza\n";
        }
        
        if(xlargePizza.isSelected()) 
        {
            amount = 13.00;
            PizzaSizes = PizzaSizes + "- Extra Large Pizza\n";
        }

        String PizzaCrusts = "";
        //Pizza Crust
        if(normalCrust.isSelected())
        {
            PizzaCrusts = PizzaCrusts + "- Normal Crust\n";
        }

        if(cheesyCrust.isSelected())
        {
            PizzaCrusts = PizzaCrusts + "- Cheesy Crust\n";
        }
        
        if(sausageCrust.isSelected())
        {
            PizzaCrusts = PizzaCrusts + "- Sausage Crust\n";
        }

        String PizzaToppings = "";
        //Pizza Toppings
        if(pepperoni.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Pepperoni\n";
        }
        
        if(extraCheese.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Extra Cheese\n";
        }
        
        if(mushroom.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Mushroom\n";
        }
        
        if(ham.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Ham\n";
        }
        
        if(bacon.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Bacon\n";
        }
        
        if(groundBeef.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Ground Beef\n";
        }
        
        if(jalapeno.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Jalapeno\n";
        }
        
        if(pineapple.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Pineapple\n";
        }
        
        if(driedShrimps.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Dried Shrimps\n";
        }
        
        if(anchovies.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Anchovies\n";
        }
        
        if(sunDriedTomatoes.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Sun Dried Tomatoes\n";
        }
        
        if(spinach.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Spinach\n";
        }
        
        if(roastedGarlic.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Roasted Garlic\n";
        }
        
        if(shreddedChicken.isSelected())
        {
            amount += 0.75;
            PizzaToppings = PizzaToppings + "- Shredded Chicken\n";
        }

        String Drinks = "";
        //Drinks
        if(coke.isSelected())
        {
            int qty = Integer.parseInt(cokeField.getText());
            amount += 1.45 * qty;
            Drinks = Drinks + "- Coke (x" + qty + ")\n";
        }

        if(dietCoke.isSelected())
        {
            int qty = Integer.parseInt(dCokeField.getText());
            amount += 1.45 * qty;
            Drinks = Drinks + "- Diet Coke (x" + qty + ")\n";
        }

        if(icedTea.isSelected())
        {
            int qty = Integer.parseInt(icedTeaField.getText());
            amount += 1.45 * qty;
            Drinks = Drinks + "- Iced Tea (x" + qty + ")\n";
        }

        if(gingerAle.isSelected())
        {
            int qty = Integer.parseInt(gingerAleField.getText());
            amount += 1.45 * qty;
            Drinks = Drinks + "-Ginger Ale (x" + qty + ")\n";
        }

        if(sprite.isSelected())
        {
            int qty = Integer.parseInt(spriteField.getText());
            amount += 1.45 * qty;
            Drinks = Drinks + "- Sprite (x" + qty + ")\n";
        }

        if(rootBeer.isSelected())
        {
            int qty = Integer.parseInt(rootBeerField.getText());
            amount += 1.45 * qty;
            Drinks = Drinks + "- Root Beer (x" + qty + ")\n";
        }

        if(water.isSelected())
        {
            int qty = Integer.parseInt(waterField.getText());
            amount += 1.25 * qty;
            Drinks = Drinks + "- Water (x" + qty + ")\n";
        }

        String OtherItems = "";
        //Others
        if(chickenWings.isSelected())
        {
            amount += 3.00;
            OtherItems = OtherItems + "- Chicken Wings\n";
        }

        if(poutine.isSelected())
        {
            amount += 3.00;
            OtherItems = OtherItems + "- Poutine\n";
        }

        if(onionRings.isSelected())
        {
            amount += 3.00;
            OtherItems = OtherItems + "- Onion Rings\n";
        }

        if(cheesyGarlicBread.isSelected())
        {
            amount += 3.00;
            OtherItems = OtherItems + "- Cheesy Garlic Bread\n";
        }

        if(garlicDip.isSelected())
        {
            OtherItems = OtherItems + "- Garlic Dip\n";
        }

        if(bbqDip.isSelected())
        {
            OtherItems = OtherItems + "- BBQ Dip\n";
        }
        
        if(sourCreamDip.isSelected())
        {
            OtherItems = OtherItems + "- Sour Cream Dip\n";
        }

        String finalDialog = ("Pizza Size\n" + PizzaSizes + nl +
                              "Pizza Crust\n" + PizzaCrusts + nl +
                              "Pizza Toppings\n" + PizzaToppings + nl +
                              "Drinks\n" + Drinks + nl +
                              "Other Items\n" + OtherItems + nl +
                              "Total: $" + amount + nl +
                              "Are you sure take your order?");

        int confirmDialog = JOptionPane.showConfirmDialog(this, finalDialog, "Confirm Order", JOptionPane.YES_NO_OPTION);
            
        if (confirmDialog == JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(this, "Order will be recieved by nearest brach and will contact you before delivery.");
            System.exit(0);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Order cancelled.");
        }
            
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeOcampo_Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeOcampo_Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeOcampo_Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeOcampo_Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeOcampo_Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JCheckBox anchovies;
    private javax.swing.JCheckBox bacon;
    private javax.swing.JCheckBox bbqDip;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnExit;
    private javax.swing.JRadioButton cheesyCrust;
    private javax.swing.JCheckBox cheesyGarlicBread;
    private javax.swing.JCheckBox chickenWings;
    private javax.swing.JCheckBox coke;
    private javax.swing.JTextField cokeField;
    private javax.swing.JTextField dCokeField;
    private javax.swing.JCheckBox dietCoke;
    private javax.swing.JCheckBox driedShrimps;
    private javax.swing.JCheckBox extraCheese;
    private javax.swing.JCheckBox garlicDip;
    private javax.swing.JCheckBox gingerAle;
    private javax.swing.JTextField gingerAleField;
    private javax.swing.JCheckBox groundBeef;
    private javax.swing.JCheckBox ham;
    private javax.swing.JCheckBox icedTea;
    private javax.swing.JTextField icedTeaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JCheckBox jalapeno;
    private javax.swing.JRadioButton largePizza;
    private javax.swing.JRadioButton mediumPizza;
    private javax.swing.JCheckBox mushroom;
    private javax.swing.JRadioButton normalCrust;
    private javax.swing.JCheckBox onionRings;
    private javax.swing.JCheckBox pepperoni;
    private javax.swing.JCheckBox pineapple;
    private javax.swing.JPanel pizzaSize;
    private javax.swing.JPanel placeOrder;
    private javax.swing.JCheckBox poutine;
    private javax.swing.JCheckBox roastedGarlic;
    private javax.swing.JCheckBox rootBeer;
    private javax.swing.JTextField rootBeerField;
    private javax.swing.JRadioButton sausageCrust;
    private javax.swing.JCheckBox shreddedChicken;
    private javax.swing.JRadioButton smallPizza;
    private javax.swing.JCheckBox sourCreamDip;
    private javax.swing.JCheckBox spinach;
    private javax.swing.JCheckBox sprite;
    private javax.swing.JTextField spriteField;
    private javax.swing.JCheckBox sunDriedTomatoes;
    private javax.swing.JCheckBox water;
    private javax.swing.JTextField waterField;
    private javax.swing.JRadioButton xlargePizza;
    // End of variables declaration//GEN-END:variables
}
